CREATE OR REPLACE TRIGGER TRIGGER1 
BEFORE INSERT OR UPDATE ON EMPLOYEES_COPY
FOR EACH ROW 
BEGIN
    IF :new.SALARY < 0  
    THEN RAISE_APPLICATION_ERROR(-20001, 'Ujemna pensja');
    ROLLBACK;
    END IF;

END;



insert into EMPLOYEES_COPY
  (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID)
  values
  (2,'pazek','Kazek','a@gmaaaco','8812-244','2018-05-12',1,-22,NULL,NULL,NULL);